$("document").ready(function(){ 
  $(".del1").click(function(){
    $(this).remove();
  });
  $(".del2").click(function(){
    $(this).remove();
  });
  $(".del3").click(function(){
    $(this).remove();
  }); 
});